//Attributfeldnamen der einzelnen Layer:
var attributeFields = [ 'Kreisname',
                        '',
                        'einwohner_.einwohner',
                        'einwohner_entwicklung_.einwohnerentwicklung',
                        'bevoelkerungsdichte_.bevölkerungsdichte',
                        'altersgruppen_._',
                        '',
                        'geburtenrate_.geburtenrate',
                        'sterberate_.sterberate',
                        'migration_gesamt_.migrationengesamt',
                        'migration_nichtdeutsch_.migrationennichtdeutsche',
                        '',
                        'pflegebeduerftige_.pflegebeduerftige',
                        'pflegeeinrichtungen_.pflegeeinrichtungen',
                        'haush',
                        'single_haushalte_.single_Haushalte',
                        'nichtdeutsche_.nichtdeutsche',
                        'migranten_.migranten',
                        'einkommen_.einkommen',
                        'konfessionen_.',
                        ''
                        ]; // used fields from the raw data

var diagramFields = new Array(attributeFields.length);

//Für die verschiedenen Layer verfügbare Jahreswerte:
var years = [   [],
                [],
                [1990, 2012, 'prognose2030'],
                ['19902012', '20122030'],
                [2012],
                [182011, 302011, 652011, 2011],
                [],
                ['20072011'],
                ['20072011'],
                ['20072011'],
                ['20072011'],
                [],
                [2011],
                [2009],
                [2010],
                [2010],
                [2011],
                [2008],
                [2009],
                ['römisch_katholisch2008_2010', 'evangelisch2008_2010', 'andere_konfessionslos2008_2010'],
                []
            ];

//Jahreswerte, welche beim Layerwechsel als erstes angezeigt werden sollen:
var initYearValues = [  0,
                        0,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ];

var timesliderLabelValues = [   [],
				                [],
				                ['1990', '2012', '2030 (Prognose)'],
				                ['1990 - 2012', '2012 - 2030 (Prognose)'],
				                ['2012'],
				                ['0 - 18 Jahre', '25 - 30 Jahre', '30 - 65 Jahre', 'über 65 Jahre'],
				                [],
				                ['2007 - 2011'],
				                ['2007 - 2011'],
				                ['2007 - 2011'],
				                ['2007 - 2011'],
				                [],
				                ['2011'],
				                ['2009'],
				                ['2010'],
				                ['2010'],
				                ['2011'],
				                ['2008'],
				                ['2009'],
				                ['Römisch-Katholisch', 'Evangelisch', 'Andere / Konfessionslos'],
				                []
				            ];

var timesliderMinLabelValues = ['',
				                '',
				                '1990',
				                '1990',
				                '',
				                '0',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                ''
				            	];

var timesliderMaxLabelValues = ['',
				                '',
				                '2030',
				                '2030',
				                '',
				                '> 65',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                '',
				                ''
				            	];

var layerNames = [ 'Kreisname',
                        '',
                        'Einwohner',
                        'Einwohnerentwicklung',
                        'Bev&ouml;lkerungsdichte',
                        'Altersgruppen',
                        '',
                        'Geburtenrate',
                        'Sterberate',
                        'Zu-/Fortzüge Gesamt',
                        'Zu-/Fortzüge Nichtdeutsche',
                        '',
                        'Pflegebed&uuml;rftige',
                        'Pflegeplätze',
                        'Haushaltsgr&ouml;ssen',
                        'Single-Haushalte',
                        'Nichtdeutsche',
                        'Migranten',
                        'Einkommen',
                        'Konfessionen',
                        ''
                        ];

var shapeNames = [
	'Bottrop',
	'Gelsenkirchen',
	'Münster',
	'Borken',
	'Coesfeld',
	'Recklinghausen',
	'Steinfurt',
	'Warendorf',
	'Bielefeld',
	'Gütersloh',
	'Herford',
	'Höxter',
	'Lippe',
	'Minden-Lübbecke',
	'Paderborn',
	'Bochum',
	'Dortmund',
	'Hagen',
	'Hamm',
	'Herne',
	'Ennepe-Ruhr-Kreis',
	'Hochsauerlandkreis',
	'Märkischer Kreis',
	'Olpe',
	'Siegen-Wittgenstein',
	'Soest',
	'Unna',
];

var defaultClassification = [
	['Bottrop',				[255,255,255,0.5]	]	,
	['Gelsenkirchen',		[255,255,255,0.5]	]	,
	['Münster',				[255,255,255,0.5]	]	,
	['Borken',				[255,255,255,0.5]	]	,
	['Coesfeld',			[255,255,255,0.5]	]	,
	['Recklinghausen',		[255,255,255,0.5]	]	,
	['Steinfurt',			[255,255,255,0.5]	]	,
	['Warendorf',			[255,255,255,0.5]	]	,
	['Bielefeld',			[255,255,255,0.5]	]	,
	['Gütersloh',			[255,255,255,0.5]	]	,
	['Herford',				[255,255,255,0.5]	]	,
	['Höxter',				[255,255,255,0.5]	]	,
	['Lippe',				[255,255,255,0.5]	]	,
	['Minden-Lübbecke',		[255,255,255,0.5]	]	,
	['Paderborn',			[255,255,255,0.5]	]	,
	['Bochum',				[255,255,255,0.5]	]	,
	['Dortmund',			[255,255,255,0.5]	]	,
	['Hagen',				[255,255,255,0.5]	]	,
	['Hamm',				[255,255,255,0.5]	]	,
	['Herne',				[255,255,255,0.5]	]	,
	['Ennepe-Ruhr-Kreis',	[255,255,255,0.5]	]	,
	['Hochsauerlandkreis',	[255,255,255,0.5]	]	,
	['Märkischer Kreis',	[255,255,255,0.5]	]	,
	['Olpe',				[255,255,255,0.5]	]	,
	['Siegen-Wittgenstein',	[255,255,255,0.5]	]	,
	['Soest',				[255,255,255,0.5]	]	,
	['Unna',				[255,255,255,0.5]	]
];

var allLayerAttributes = [
	//[dataset, 'Title (String)', 'Value (String)', 'Legend-description']
	[datenEinwohner, 'Einwohner', '', ''],
	[datenEinwohnerEntwicklung, 'Einwohner-Entwicklung', '&#037;', ''],
	[datenBevoelkerungsdichte, 'Bevölkerungsdichte', '', 'Einheit: Einwohner pro km&sup2;'],
	[datenAltersgruppen, 'Altersgruppen 2011', '&#037;', ''],
	[datenGeburtenrate, 'Geburtenrate', '&permil;', ''],
	[datenSterberate, 'Sterberate', '&permil;', ''],
	[datenMigrationenGesamt, 'Zu-/Fortzüge (gesamt)', '&permil;', ''],
	[datenMigrationenNichtdeutsche, 'Zu-/Fortzüge (Nichtdeutsche)', '&permil;', ''],
	[datenPflegebeduerftige, 'Pflegebedürftige', '&permil;', ''],
	[datenPflegeeinrichtungen, 'Pflegeplätze', '', 'je 100000 Einwohner'],
	[datenHaushaltsgroesse, 'Haushaltsgröße', 'Personen', ''],
	[datenSingleHaushalte, 'Single-Haushalte', '&#037;', ''],
	[datenNichtdeutsche, 'Nichtdeutsche', '&#037;', ''],
	[datenMigranten, 'Migranten', '&#037;', ''],
	[datenEinkommen, 'Einkommen', '&euro;', '&euro; je Einw.'],
	[datenKonfessionen, 'Konfessionen 2008 - 2010', '&#037;', '']
];